# -*- coding: utf-8 -*-
"""week 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npOEwvkiSXKNpN7MACy-JTbjRcNHRd2i
"""

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir("/content/drive/MyDrive/Week_7_Tut_Lab_Activities/Assets/insects_dataset"))

print(os.listdir("/content/drive/MyDrive/Week_7_Tut_Lab_Activities/Assets/insects_dataset/train_data"))

"""### **Step 1**"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing import image

# === USER VARIABLES ===
DATASET_DIR = "/content/drive/MyDrive/Week_7_Tut_Lab_Activities/Assets/insects_dataset/train_data"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 123

print("Loading dataset with 80/20 train-validation split...")

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    DATASET_DIR,
    validation_split=0.2,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    DATASET_DIR,
    validation_split=0.2,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f"Classes found: {class_names}")

"""## Step 2"""

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

"""## **Step 3**"""

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
])

# Visualize some augmented images
plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
    augmented_images = data_augmentation(images)
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(augmented_images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")
plt.show()

"""## **Step 4**"""

base_model = tf.keras.applications.MobileNetV2(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False  # Freeze the base model initially

inputs = layers.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = tf.keras.applications.mobilenet_v2.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(num_classes, activation='softmax')(x)

model = models.Model(inputs, outputs)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""## **Step 5**"""

EPOCHS = 10

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

"""## **Step 6**"""

initial_acc = history.history['accuracy']
initial_val_acc = history.history['val_accuracy']
initial_loss = history.history['loss']
initial_val_loss = history.history['val_loss']

epochs_range = range(EPOCHS)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, initial_acc, label='Training Accuracy')
plt.plot(epochs_range, initial_val_acc, label='Validation Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, initial_loss, label='Training Loss')
plt.plot(epochs_range, initial_val_loss, label='Validation Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()

"""## **Step 7**"""

val_loss, val_acc = model.evaluate(val_ds)
print(f'Validation accuracy: {val_acc*100:.2f}%')

"""## **Step 9**"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %cd /content/drive/MyDrive/2026_Teaching/ST1/Week_7_Tut_Lab_Activities

model.save('macroinvertebrates_classifier.h5')

print("Model saved as 'macroinvertebrates_classifier.h5'")

"""## **Step 10**"""

# === STEP 10: Evaluation (Confusion Matrix, Precision, Recall, F1, ROC) ===

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_recall_fscore_support, roc_curve, auc
from sklearn.preprocessing import label_binarize
import tensorflow as tf

# Step 10.1: Collect predictions
y_true = []
y_pred = []
y_scores = []

for images, labels in val_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))
    y_scores.extend(preds)

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_scores = np.array(y_scores)

# Step 10.2: Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)

plt.figure(figsize=(12, 12))
disp.plot(cmap=plt.cm.Blues, xticks_rotation='vertical')
plt.title('Confusion Matrix on Validation Set')
plt.show()

# Step 10.3: Precision, Recall, F1
precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted')

print(f"Weighted Precision: {precision:.4f}")
print(f"Weighted Recall: {recall:.4f}")
print(f"Weighted F1-score: {f1:.4f}")

# Step 10.4: ROC Curve
y_true_bin = label_binarize(y_true, classes=range(len(class_names)))
n_classes = y_true_bin.shape[1]

plt.figure(figsize=(14, 12))

for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_scores[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, lw=2, label=f'{class_names[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate (FPR)")
plt.ylabel("True Positive Rate (TPR)")
plt.title("ROC Curves for Each Class")
plt.legend(loc="lower right")
plt.show()

"""## **Step 12**"""

# === STEP 12: Inference on new images inside class subfolders ===

import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

TEST_IMAGE_DIR = '/content/drive/MyDrive/Week_7_Tut_Lab_Activities/Assets/insects_dataset/test_data'

def load_and_preprocess_image(img_path, img_size=IMG_SIZE):
    img = image.load_img(img_path, target_size=img_size)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def predict_new_images(test_dir):
    img_files = []
    for root, dirs, files in os.walk(test_dir):
        for f in files:
            if f.lower().endswith(('.jpg', '.jpeg', '.png')):
                img_files.append(os.path.join(root, f))

    if not img_files:
        print(f"No images found in '{test_dir}'.")
        return

    for path in img_files:
        img_arr = load_and_preprocess_image(path)

        preds = model.predict(img_arr, verbose=0)
        pred_idx = np.argmax(preds[0])
        confidence = preds[0][pred_idx]

        file_name = os.path.basename(path)
        true_folder = os.path.basename(os.path.dirname(path))

        print(f"Image: {file_name}")
        print(f"Actual folder: {true_folder}")
        print(f"Predicted: {class_names[pred_idx]} ({confidence*100:.2f}%)")

        img = image.load_img(path)
        plt.imshow(img)
        plt.title(f"Actual: {true_folder}\nPredicted: {class_names[pred_idx]} ({confidence*100:.2f}%)")
        plt.axis("off")
        plt.show()

print("Running inference...")
predict_new_images(TEST_IMAGE_DIR)